services:
    watchtower:
        image: containrrr/watchtower:${watchtowerVersion}
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./.env
        environment:
            - TZ=${TZ}
            - WATCHTOWER_CLEANUP=false
            - WATCHTOWER_LABEL_ENABLE=true
#            - WATCHTOWER_INCLUDE_RESTARTING=true
#            - WATCHTOWER_MONITOR_ONLY=true
            - WATCHTOWER_SCHEDULE= 0 0 13 * * * # runs daily at 1300
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER-SMTP-EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER-SMTP-EMAIL-TO}
            - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Watchtower Alert - Container Updates
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER-SMTP-SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER-SMTP-PASSWORD}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER-SMTP-EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
        labels:
            - "com.centurylinklabs.watchtower.monitor-only"
        restart: unless-stopped